#
# (C) Copyright 2013
# Kentaro Sekimoto
#
# Based on emcraft implementation.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-$(CONFIG_MACH_FM3)		+= fm3_platform.o timer.o clock.o reboot.o
obj-$(CONFIG_GPIOLIB)		+= gpio.o
obj-$(CONFIG_SERIAL_FM3)	+= uart.o
obj-$(CONFIG_FM3_ETH)		+= eth.o
obj-$(CONFIG_SPI_FM3)		+= spi.o
obj-$(CONFIG_I2C_FM3)		+= i2c.o
obj-$(CONFIG_I2C_GPIO)		+= i2c-gpio.o
obj-$(CONFIG_MTD_PHYSMAP)	+= flash.o
obj-$(CONFIG_MMC_SPI)		+= sdcard.o
obj-$(CONFIG_USB_FM3_HCD)	+= usb.o
